"""
MediGuard V2 — Report API Routes (Phase 4 — Pipeline Wired)

POST /report/generate   → triggers background pipeline via FastAPI BackgroundTasks
GET  /report/{id}       → polls report completion status
GET  /report/{id}/audit → returns HIPAA audit trail for the session
"""
import asyncio
from uuid import UUID
from fastapi import APIRouter, BackgroundTasks, Depends, status
from fastapi.responses import JSONResponse, RedirectResponse

from supabase import Client
from app.dependencies import get_db, verify_clinical_auth
from app.schemas.report import ReportRequest, ClinicalReportResponse
from app.services.patient_service import PatientService
from app.services.report_service import ReportService
from app.services.audit_service import AuditService
from app.utils.logger import get_logger

logger = get_logger("app.api.v1.report")
router = APIRouter()


# ─────────────────────────────────────────────────────────────────────────────
# Background pipeline task
# ─────────────────────────────────────────────────────────────────────────────

async def run_pipeline_background(
    session_id: str,
    patient_data: dict,
    db: Client,
) -> None:
    """
    Background task: runs the full MediGuard clinical pipeline, persists the
    generated report, and updates session status on both success and failure.

    This function is intentionally fully self-contained with its own
    exception handling — it must never crash silently.
    """
    from app.agents.orchestrator import orchestrator

    logger.info("Background pipeline task starting", session_id=session_id)

    audit_service  = AuditService(db)
    patient_service = PatientService(db, audit_service)
    report_service = ReportService(db, audit_service)

    try:
        # ── Run the full LangGraph multi-agent pipeline ───────────────────────
        final_state = await orchestrator.run_pipeline(session_id, patient_data)

        report_data     = final_state.get("report", {})
        ddx_list        = final_state.get("differential_diagnosis", [])
        drug_interactions = final_state.get("drug_interactions", [])
        urgency_level   = final_state.get("urgency_level", "medium")
        completed_agents = final_state.get("completed_agents", [])

        # Extract recommended tests from the report object or DDx
        recommended_tests = report_data.get(
            "recommended_workup",
            _extract_tests_from_ddx(ddx_list),
        )

        # Build the report persistence payload
        report_payload = {
            "differential_diagnosis":  ddx_list,
            "recommended_tests":       recommended_tests,
            "drug_interactions_found": drug_interactions,
            "clinical_summary":        report_data.get(
                "clinical_narrative",
                report_data.get("executive_summary", "Report generated by MediGuard V2.")
            ),
            "urgency_level":           urgency_level,
            "reviewed_by_agent":       "MediGuardOrchestrator v2",
            "fhir_bundle":             {},
        }

        # ── Persist the clinical report ───────────────────────────────────────
        await report_service.save_report(UUID(session_id), report_payload)

        # ── Generate clinical visual PDF and structured FHIR bundle ──────────────────
        logger.info("Triggering clinical document generation workflow in background task", session_id=session_id)
        from app.services.document_service import DocumentService
        document_service = DocumentService(db)

        # Build comprehensive report payload matching visual components
        doc_report_data = {
            "differential_diagnosis": ddx_list,
            "recommended_workup": recommended_tests,
            "drug_interactions": drug_interactions,
            "urgency_level": urgency_level,
            "urgency_assessment": final_state.get("urgency_assessment", report_data.get("urgency_assessment", f"Urgency level assessed as {urgency_level}.")),
            "executive_summary": report_data.get("executive_summary", "Clinical decision support summary for patient session."),
            "clinical_narrative": report_data.get("clinical_narrative", ""),
            "disposition_recommendation": report_data.get("disposition_recommendation", "N/A"),
            "follow_up_instructions": report_data.get("follow_up_instructions", []),
            "differential_summary": report_data.get("differential_summary", ""),
            "clinical_disclaimers": report_data.get("clinical_disclaimers", [
                "This report is AI-generated clinical decision support only.",
                "All recommendations must be reviewed by a licensed physician.",
                "This system does not replace clinical judgment."
            ]),
            "primary_diagnosis": report_data.get("primary_diagnosis", {}),
            "contraindications": final_state.get("contraindications", report_data.get("contraindications", [])),
            "medication_notes": final_state.get("medication_notes", report_data.get("medication_notes", "")),
            "fda_data_used": final_state.get("fda_data_used", False),
            "report_metadata": {
                "agents_used": completed_agents,
                "generation_time_seconds": final_state.get("report_metadata", {}).get("generation_time_seconds", 15.0),
                "model_used": final_state.get("report_metadata", {}).get("model_used", "MediGuard Clinical AI"),
                "rag_sources_count": final_state.get("report_metadata", {}).get("rag_sources_count", 0)
            }
        }

        doc_res = await document_service.generate_clinical_documents(
            session_id=session_id,
            report_data=doc_report_data,
            patient_data=patient_data
        )

        # ── Mark session as completed ─────────────────────────────────────────
        await patient_service.update_session_status(UUID(session_id), "completed")

        await audit_service.log_action(
            action="pipeline_completed",
            actor="orchestrator",
            session_id=UUID(session_id),
            metadata={
                "agents_completed": completed_agents,
                "urgency_level":    urgency_level,
                "report_generated": final_state.get("report_generated", False),
                "pdf_url":          doc_res.get("pdf_url"),
                "fhir_valid":       doc_res.get("fhir_valid")
            },
        )

        logger.info(
            "Background pipeline task completed successfully with document compilation",
            session_id=session_id,
            urgency=urgency_level,
            agents_run=completed_agents,
            pdf_url=doc_res.get("pdf_url")
        )

    except Exception as exc:
        logger.error(
            "Background pipeline task FAILED",
            session_id=session_id,
            error=str(exc),
        )
        try:
            # Best-effort: update session status to failed so the client knows
            audit_service  = AuditService(db)
            patient_service = PatientService(db, audit_service)
            await patient_service.update_session_status(UUID(session_id), "failed")
            await audit_service.log_action(
                action="pipeline_failed",
                actor="orchestrator",
                session_id=UUID(session_id),
                metadata={"error": str(exc)},
            )
        except Exception as inner_exc:
            logger.error(
                "Could not mark session as failed after pipeline error",
                session_id=session_id,
                inner_error=str(inner_exc),
            )


# ─────────────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/generate", status_code=status.HTTP_202_ACCEPTED)
async def generate_report(
    request: ReportRequest,
    background_tasks: BackgroundTasks,
    db: Client = Depends(get_db),
    actor: dict = Depends(verify_clinical_auth),
):
    """
    Trigger the multi-agent CDSS analysis pipeline for a patient session.

    Immediately returns 202 Accepted. The pipeline runs in the background.
    Poll GET /report/{session_id} to check for completion.
    """
    logger.info(
        "Received request to trigger report generation",
        session_id=request.session_id,
    )

    audit_service  = AuditService(db)
    patient_service = PatientService(db, audit_service)
    report_service = ReportService(db, audit_service)

    # 1. Validate patient session exists
    session = await patient_service.get_session(request.session_id, actor=actor.get("username", "system"))

    # 2. Short-circuit if already completed
    if session.status == "completed":
        logger.info(
            "Session already completed — returning existing report reference",
            session_id=request.session_id,
        )
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content={
                "session_id": str(request.session_id),
                "status":     "completed",
                "message":    "Report already generated. Use GET /report/{session_id} to retrieve.",
            },
        )

    # 3. Short-circuit if already running
    if session.status == "processing":
        logger.info(
            "Pipeline already running for session",
            session_id=request.session_id,
        )
        return JSONResponse(
            status_code=status.HTTP_202_ACCEPTED,
            content={
                "session_id": str(request.session_id),
                "status":     "processing",
                "message":    "Report generation already in progress. Poll GET /report/{session_id}.",
            },
        )

    # 4. Mark session as processing
    await patient_service.update_session_status(request.session_id, "processing")

    # 5. Build patient_data dict from session object for the pipeline
    patient_data = {
        "patient_name":        session.patient_name,
        "patient_age":         session.patient_age,
        "patient_gender":      session.patient_gender,
        "chief_complaint":     session.chief_complaint,
        "symptoms":            session.symptoms,
        "medical_history":     session.medical_history,
        "current_medications": session.current_medications,
        "allergies":           session.allergies,
        "vitals":              session.vitals,
    }

    # 6. Enqueue background pipeline task
    background_tasks.add_task(
        run_pipeline_background,
        str(request.session_id),
        patient_data,
        db,
    )

    logger.info(
        "Pipeline enqueued in background",
        session_id=request.session_id,
    )

    return {
        "session_id": str(request.session_id),
        "status":     "processing",
        "message":    "Report generation initiated. State transitioned to processing.",
    }


@router.get("/{session_id}", status_code=status.HTTP_200_OK)
async def get_report(
    session_id: UUID,
    db: Client = Depends(get_db),
    actor: dict = Depends(verify_clinical_auth),
):
    """
    Poll report completion status.

    Returns the clinical report if completed, or status + polling instructions
    if still processing.
    """
    logger.info(
        "Received request to retrieve clinical report results",
        session_id=session_id,
    )

    audit_service  = AuditService(db)
    patient_service = PatientService(db, audit_service)
    report_service = ReportService(db, audit_service)

    # Check session status first — fail-fast if not ready
    session = await patient_service.get_session(session_id, actor=actor.get("username", "system"))

    if session.status == "processing":
        return JSONResponse(
            status_code=status.HTTP_202_ACCEPTED,
            content={
                "session_id": str(session_id),
                "status":     "processing",
                "message":    "Clinical pipeline is still running. Please try again in a few seconds.",
            },
        )

    if session.status == "failed":
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={
                "session_id": str(session_id),
                "status":     "failed",
                "message":    "Clinical pipeline failed. Please re-trigger or contact support.",
            },
        )

    report = await report_service.get_report(session_id)
    return report


@router.get("/{session_id}/audit", status_code=status.HTTP_200_OK)
async def get_report_audit(
    session_id: UUID,
    db: Client = Depends(get_db),
    actor: dict = Depends(verify_clinical_auth),
):
    """
    Returns the complete HIPAA action audit trail associated with the session.
    """
    logger.info(
        "Received request to retrieve clinical session audit log trails",
        session_id=session_id,
    )

    audit_service  = AuditService(db)
    patient_service = PatientService(db, audit_service)

    # Validate session exists first
    await patient_service.get_session(session_id, actor=actor.get("username", "system"))

    audit_trail = await audit_service.get_session_audit_trail(session_id)
    return audit_trail


# ── Utility ───────────────────────────────────────────────────────────────────

def _extract_tests_from_ddx(ddx_list: list) -> list:
    """Extract recommended tests from the DDx list as a fallback."""
    tests = []
    for ddx in ddx_list:
        if isinstance(ddx, dict):
            pass  # DDx list doesn't carry tests — just return empty
    return tests


# ─────────────────────────────────────────────────────────────────────────────
# Document Retrieval Routes
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/{session_id}/pdf", status_code=status.HTTP_307_TEMPORARY_REDIRECT)
async def get_report_pdf(
    session_id: UUID,
    db: Client = Depends(get_db),
    actor: dict = Depends(verify_clinical_auth),
):
    """
    Returns a 307 temporary redirect to the compiled PDF report stored in Supabase Storage.
    Returns 404 with error details if the PDF has not been generated yet.
    """
    logger.info("Received request to retrieve PDF report redirect URL", session_id=session_id)
    report_service = ReportService(db, AuditService(db))
    try:
        report = await report_service.get_report(session_id)
        if not report.report_pdf_url:
            return JSONResponse(
                status_code=status.HTTP_404_NOT_FOUND,
                content={"error": True, "message": "PDF not yet generated. Check report status."}
            )
            
        return RedirectResponse(
            url=report.report_pdf_url,
            status_code=status.HTTP_307_TEMPORARY_REDIRECT
        )
    except Exception as e:
        logger.error("Failed to retrieve PDF report redirect URL", session_id=session_id, error=str(e))
        return JSONResponse(
            status_code=status.HTTP_404_NOT_FOUND,
            content={"error": True, "message": "PDF not yet generated. Check report status."}
        )


@router.get("/{session_id}/fhir", status_code=status.HTTP_200_OK)
async def get_fhir_bundle(
    session_id: UUID,
    db: Client = Depends(get_db),
    actor: dict = Depends(verify_clinical_auth),
):
    """
    Returns the raw FHIR bundle JSON object compiled for this session.
    """
    logger.info("Received request to retrieve FHIR bundle JSON", session_id=session_id)
    report_service = ReportService(db, AuditService(db))
    try:
        report = await report_service.get_report(session_id)
        if not report.fhir_bundle:
            return JSONResponse(
                status_code=status.HTTP_404_NOT_FOUND,
                content={"error": True, "message": "FHIR bundle not yet generated. Check report status."}
            )
            
        return JSONResponse(
            content=report.fhir_bundle,
            media_type="application/fhir+json",
            headers={"X-FHIR-Version": "4.0.1"}
        )
    except Exception as e:
        logger.error("Failed to retrieve FHIR bundle JSON", session_id=session_id, error=str(e))
        return JSONResponse(
            status_code=status.HTTP_404_NOT_FOUND,
            content={"error": True, "message": f"FHIR bundle not found. Details: {str(e)}"}
        )

